<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;
use AppBundle\Entity\Comment;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllByArticleId($id){
        $qb = $this->createQuerybuilder('article')
        ->select('article', 'comment', 'user')
        ->leftJoin('article.comments', 'comment')
        ->leftJoin('article.user', 'user')
        ->andWhere('article.id = :id')
        ->setParameter(':id',$id)
        ->orderBy('article.id','asc');
        return $qb->getQuery()->getSingleResult();
    }
}

// SELECT a.*, c.* , u.*
// FROM article a
// LEFT JOIN comment c ON (a.id = c.article_id)
// LEFT JOIN fos_user u ON (u.id = a.user_id)
// WHERE a.id = 2

// SELECT a.*, c.* , u.*
// FROM article a
// LEFT JOIN comment c ON (a.id = c.article_id)
// LEFT JOIN fos_user u ON (u.id = a.user_id)
// ORDER BY a.id ASC