<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;
use AppBundle\Entity\Comment;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllByArticleId($id){
        $qb = $this->createQuerybuilder('article')
        ->select('article')
        ->add('from', new Expr\From(Article::article,'article'),false)
        ->innerJoin('article.comment', 'comment')
        ->andWhere('comment.id = :id')
        ->setParameter(':id', $id)
        ->orderBy('article.id','asc');
        return $qb->getQuery()->getresult();
    }
}
