<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;
use AppBundle\Entity\Comment;


/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllByCommentId($id){
        $qb = $this->createQueryBuilder('comment')
        ->select('comment')
        ->add('from',new Expr\From(Comment::class,'comment'),false)
        ->innerJoin('comment.article','article')
        ->andWhere('article.id = :id')
        ->setParameter(':id',$id)
        ->orderBy('comment.id','asc');
        return $qb->getQuery()->getResult();
    }

}
