<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr as Expr;
use AppBundle\Entity\Comment;


/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    function findAllByCommentId($id){
     $this->createQueryBuilder('comment')
     ->select('comment')
     ->add('from',new Expr\From(Comment::class,'comment'),false)
     ->andWhere('comment.article_id = :id')
     ->setParameter(':id',$id)
     ->orderBy('comment.id','asc');
    }
}
