app_article:
    resource: "@AppBundle/Resources/config/routing/article.yml"
    prefix:   /article
app_comment:
    resource: "@AppBundle/Resources/config/routing/comment.yml"
    prefix:   /comment
app_user:
    resource: "@AppBundle/Resources/config/routing/user.yml"
    prefix:   /user
