AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        image:
            type: string
            length: 255
        createdAt:
            type: datetime
            DateTime: ~
            nullable: false 
    lifecycleCallbacks: {  }
    oneToMany:
        comments:
            targetEntity: AppBundle\Entity\Comment
            mappedBy: article
            onDelete: CASCADE
            onUpdate: CASCADE
            cascade: [remove]
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            inversedBy: articles
            joinColumn:
                nullable: true

