AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
    lifecycleCallbacks: {  }
    oneToMany:
        comments:
            targetEntity: AppBundle\Entity\Comment
            mappedBy: article