AppBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        content:
            type: text
    lifecycleCallbacks: {  }
    manyToOne:
        article:
            targetEntity: AppBundle\Entity\Article
            inversedBy: comments
            joinColumn:
                nullable: true
              
